[package]
name = "procview"
version = "0.1.0"
authors = ["Jack Barnes <barnesjt05@gmail.com>"]
edition = "2018"

[dependencies]
sysinfo = "0.9.0"
procfs = "0.5.3"
benfred-read-process-memory = "0.1.4"
hex = "0.3.2"